// Content Intelligence Engine — Public API
// Phases 2–6: Provider abstraction, generation orchestration, quality validation, content intelligence, construction
//
// Import from here to use the Content Intelligence Engine.

// ─── Types ──────────────────────────────────────────────────────────────────
export type {
  Provider,
  ProviderCapability,
  ProviderConfig,
  ProviderStatus,
  Model,
  ModelType,
  ModelCapabilities,
  AspectRatio,
  GenerationRequest,
  GenerationInput,
  JobSubmission,
  JobStatus,
  JobStatusType,
  JobResult,
  JobResultMetadata,
} from './providers/types';

// ─── Registry ───────────────────────────────────────────────────────────────
export { ProviderRegistry, providerRegistry } from './providers/registry';

// ─── Router ─────────────────────────────────────────────────────────────────
export { ModelRouter, modelRouter } from './providers/router';
export type { RoutingCriteria, RoutingResult } from './providers/router';

// ─── Adapters ───────────────────────────────────────────────────────────────
export { FalAdapter } from './providers/fal-adapter';
export { ElevenLabsAdapter } from './providers/elevenlabs-adapter';

// ─── Generation Factory ─────────────────────────────────────────────────────
export {
  GenerationFactory,
  getFactory,
  resetFactory,
  GenerationError,
} from './generation';
export type {
  GenerationRequest as FactoryGenerationRequest,
  GenerationJobRecord,
  GenerationJobStatus,
  GenerationAttemptRecord,
  GenerationAttemptStatus,
  GenerationJobOutput,
  GenerationJobAudioOutput,
  WebhookEvent,
  GenerationFactoryOptions,
  GenerationErrorCode,
} from './generation';

// ─── Quality Validation ─────────────────────────────────────────────────────
export {
  MediaProcessor,
  getMediaProcessor,
  resetMediaProcessor,
  AudioValidator,
  getAudioValidator,
  resetAudioValidator,
  VideoValidator,
  getVideoValidator,
  resetVideoValidator,
  ImageValidator,
  getImageValidator,
  resetImageValidator,
  QualityGate,
  getQualityGate,
  resetQualityGate,
  isHardFailure,
  isRetryableFailure,
  DEFAULT_AUDIO_CONFIG,
  DEFAULT_VIDEO_CONFIG,
  DEFAULT_IMAGE_CONFIG,
  DEFAULT_PROCESSOR_CONFIG,
} from './quality';
export type {
  MediaType,
  MediaProcessingStatus,
  FailureCode,
  AudioValidationStatus,
  AudioMetadata,
  AudioValidationConfig,
  VideoValidation,
  VideoValidationConfig,
  ImageValidation,
  ImageValidationConfig,
  QualityScores,
  QualityAssessment,
  QualityGateResult,
  ProcessingMetadata,
  MediaProcessingResult,
  NormalizedMetadata,
  MediaProcessorConfig,
} from './quality';

// ─── Content Intelligence ───────────────────────────────────────────────────
export {
  TaggingEngine,
  getTaggingEngine,
  resetTaggingEngine,
  TagNormalizer,
  getTagNormalizer,
  resetTagNormalizer,
  ImageAnalyzer,
  getImageAnalyzer,
  resetImageAnalyzer,
  VideoAnalyzer,
  getVideoAnalyzer,
  resetVideoAnalyzer,
  EmbeddingService,
  getEmbeddingService,
  resetEmbeddingService,
  DEFAULT_TAGGING_CONFIG,
} from './intelligence';
export type {
  TagCategory,
  TagSource,
  Tag,
  AssetTag,
  AssetAnalysis,
  AnalyzedTag,
  DetectedEntity,
  ContentIntent,
  BusinessContext,
  VideoFormat,
  VideoStyle,
  AnalysisMetadata,
  EmbeddingMetadata,
  EmbeddingType,
  StoredEmbedding,
  TaggingEngineConfig,
  AssetSearchCriteria,
  AssetSearchResult,
  SimilaritySearchCriteria,
  TaggingRun,
} from './intelligence';

// ─── Content Construction ────────────────────────────────────────────────────
export {
  ConstructionEngine,
  getConstructionEngine,
  ContentQualificationEngine,
  getContentQualificationEngine,
  SlideshowMatcher,
  getSlideshowMatcher,
  TextGenerator,
  getTextGenerator,
  AudioSelector,
  getAudioSelector,
  CompositionQualityEvaluator,
  getCompositionQualityEvaluator,
  DEFAULT_CONSTRUCTION_CONFIG,
} from './construction';
export type {
  SlotDefinition,
  SlotSchema,
  SlotValue,
  PopulatedSlots,
  QualificationRules,
  QualificationResult,
  ConstructionRules,
  ConstructionPlan,
  SlideText,
  TextPosition,
  TextStyle,
  AudioPlan,
  CompositionMetadata,
  ContentComposition,
  LibraryContent,
  ContentStatus,
  ProvenanceChain,
  ConstructionFailure,
  ConstructionEngineConfig,
} from './construction';

// ─── Inventory Intelligence ──────────────────────────────────────────────────
export {
  DeduplicationEngine,
  getDeduplicationEngine,
  DiversityEngine,
  getDiversityEngine,
  InventoryEngine,
  getInventoryEngine,
  DemandEngine,
  getDemandEngine,
  DEFAULT_INVENTORY_CONFIG,
  DEFAULT_INVENTORY_ENGINE_CONFIG,
  DEFAULT_DECAY_RATES,
} from './inventory';
export type {
  DuplicateGroup,
  DuplicateType,
  DeduplicationResult,
  CompositionSignature,
  DiversityDimension,
  ContentDistribution,
  DistributionEntry,
  DiversityImbalance,
  DiversityScore,
  InventoryStatus,
  InventorySnapshot,
  InventoryHealth,
  FreshnessScore,
  FreshnessCategory,
  DecayRate,
  GenerationDemand,
  DemandPriority,
  DemandStatus,
  GenerationBrief,
  BriefRequirement,
  DemandMetadata,
  CoverageReport,
  ContentTypeCoverage,
  DimensionCoverage,
  CategoryCoverage,
  CoverageGap,
  ContentCluster,
  ClusterType,
  InventoryAnalytics,
  AnalyticsPeriod,
  InventoryEngineConfig,
  InventoryConfig,
} from './inventory';

// ─── Autonomous Factory ─────────────────────────────────────────────────────
export {
  FactoryScheduler,
  getFactoryScheduler,
  resetFactoryScheduler,
  DemandPrioritizer,
  getDemandPrioritizer,
  resetDemandPrioritizer,
  BudgetController,
  getBudgetController,
  resetBudgetController,
  ModelLearner,
  getModelLearner,
  resetModelLearner,
  QualityRecovery,
  getQualityRecovery,
  resetQualityRecovery,
  DiversityController,
  getDiversityController,
  resetDiversityController,
  SelfReplenisher,
  getSelfReplenisher,
  resetSelfReplenisher,
  DEFAULT_SCHEDULER_CONFIG,
  DEFAULT_PRIORITIZATION_CONFIG,
  DEFAULT_BUDGET_CONFIG,
  DEFAULT_AUTONOMOUS_CONFIG,
} from './autonomous';
export type {
  FactorySchedulerConfig,
  FactoryRun,
  FactoryRunPhase,
  FactoryRunStatus,
  FactoryRunMetrics,
  FactoryHealth,
  FactoryIssue,
  DemandPriorityScore,
  PrioritizationConfig,
  BudgetConfig,
  BudgetStatus,
  BudgetPeriod,
  CostRecord,
  ModelPerformance,
  RoutingRecommendation,
  RecoveryStrategy,
  RecoveryType,
  RecoveryModification,
  RecoveryAttempt,
  DiversityTarget,
  DiversityAction,
  DiversityControlResult,
  AutonomousFactoryConfig,
} from './autonomous';

// ─── Factory Validation ─────────────────────────────────────────────────────
export {
  DryRunEngine,
  getDryRunEngine,
  resetDryRunEngine,
  SandboxExecutor,
  getSandboxExecutor,
  resetSandboxExecutor,
  KillSwitch,
  getKillSwitch,
  resetKillSwitch,
  ProvenanceAuditor,
  getProvenanceAuditor,
  resetProvenanceAuditor,
  QualityInvariantTester,
  getQualityInvariantTester,
  resetQualityInvariantTester,
  CostAccuracyTracker,
  getCostAccuracyTracker,
  resetCostAccuracyTracker,
  SafetyLimitsEngine,
  getSafetyLimitsEngine,
  resetSafetyLimitsEngine,
  ProductionActivationGuard,
  getProductionActivationGuard,
  resetProductionActivationGuard,
  EndToEndAcceptanceTest,
  getEndToEndAcceptanceTest,
  resetEndToEndAcceptanceTest,
  DEFAULT_DRY_RUN_CONFIG,
  DEFAULT_SANDBOX_CONFIG,
  DEFAULT_KILL_SWITCH,
  DEFAULT_SAFETY_LIMITS,
} from './validation';
export type {
  DryRunConfig,
  DryRunResult,
  DryRunInventoryStatus,
  DryRunDemand,
  DryRunPrioritizedTask,
  DryRunBudgetProjection,
  DryRunModelSelection,
  SandboxConfig,
  SandboxResult,
  EndToEndTest,
  EndToEndStep,
  TestAssertion,
  ProvenanceNode,
  ProvenanceLevel,
  ProvenanceAudit,
  QualityInvariantTest,
  InvariantTestSuite,
  CostAccuracyReport,
  KillSwitchState,
  SafetyLimits,
  SafetyCheck,
  ProductionActivation,
  ProductionGate,
} from './validation';
