import { and, desc, eq, gte, lte } from 'drizzle-orm';
import type { Metadata } from 'next';

// import { redirect } from 'next/navigation';
import { BlitzDailyView } from '@/components/campaigns/BlitzDailyView';
import { getAuthContext } from '@/lib/auth';
import { getOrgBillingState } from '@/lib/billing';
import { resolveBlitzTargetAccounts } from '@/lib/blitz/resolve-target-accounts';
import { getDb } from '@/libs/DB';
import { campaignContentSchema, campaignSchema, contentAngleSchema, contentItemSchema, socialAccountSchema } from '@/models/Schema';

export const metadata: Metadata = {
  title: 'Blitz | NativPost',
  description: 'Your daily content queue',
};

const DEFAULT_BLITZ = {
  name: 'Today\'s Blitz',
  description: 'Daily content queue generated by Blitz',
  contentMix: {
    slideshow: 17,
    greenScreen: 0,
    videoHook: 0,
    talkingHead: 25,
    videoHookDemo: 33,
    ugc: 25,
  },
  remixRatio: 100,
  angles: [] as { angleId: string; weight: number }[],
  mentionFrequency: 'sometimes' as const,
  genderPreference: null as string | null,
  ownMediaMix: 50,
  influencerFrequency: 0,
  // Blitz derives publish targets at read time from
  //   connectedAccounts − blitzDisabledAccountIds
  // so we leave targetAccounts empty for new Blitz campaigns and rely on
  // blitzDisabledAccountIds instead. Regular campaigns are unaffected.
  targetAccounts: [] as { accountId: string; platform: string }[],
  blitzDisabledAccountIds: [] as string[],
  postsPerDay: 10,
  campaignLengthDays: 1,
  qualityThreshold: 0.7,
  reRollsRemaining: 4,
  status: 'draft' as const,
};

export default async function Page() {
  const db = await getDb();
  const { error, orgId } = await getAuthContext();

  if (error || !orgId) {
    return <p className="py-8 text-body text-muted-foreground">Please sign in to view Blitz.</p>;
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);

  // Find today's Blitz campaign
  const [existing] = await db
    .select()
    .from(campaignSchema)
    .where(
      and(
        eq(campaignSchema.orgId, orgId),
        eq(campaignSchema.name, 'Today\'s Blitz'),
        gte(campaignSchema.createdAt, today),
        lte(campaignSchema.createdAt, tomorrow),
      ),
    )
    .orderBy(desc(campaignSchema.createdAt))
    .limit(1);

  let campaign = existing;

  // Always load the org's connected social accounts — they're needed for
  // the effective-targets derivation whether or not we create a fresh
  // Blitz campaign row this request.
  const connectedAccounts = await db
    .select()
    .from(socialAccountSchema)
    .where(and(eq(socialAccountSchema.orgId, orgId), eq(socialAccountSchema.isActive, true)));

  if (!campaign) {
    const angles = await db
      .select()
      .from(contentAngleSchema)
      .where(and(eq(contentAngleSchema.orgId, orgId), eq(contentAngleSchema.isActive, true)))
      .limit(5);

    const startDate = new Date();
    startDate.setDate(startDate.getDate() + 1);

    // Clamp the default posts/day to the plan cap so fresh Trial users
    // don't land on a value they can't sustain. -1 = unlimited.
    const billing = await getOrgBillingState(orgId);
    const cap = billing?.features?.blitzPostsPerDay ?? -1;
    const initialPostsPerDay = cap === -1
      ? DEFAULT_BLITZ.postsPerDay
      : Math.min(DEFAULT_BLITZ.postsPerDay, cap);

    const campaignAngles = angles.map(a => ({ angleId: a.id, weight: Math.round(100 / Math.max(angles.length, 1)) }));

    // Normalize weights to sum to 100
    if (campaignAngles.length > 0) {
      const total = campaignAngles.reduce((sum, a) => sum + a.weight, 0);
      if (total !== 100 && total > 0) {
        const first = campaignAngles[0];
        if (first) {
          first.weight += 100 - total;
        }
      }
    }

    const [created] = await db
      .insert(campaignSchema)
      .values({
        orgId,
        ...DEFAULT_BLITZ,
        postsPerDay: initialPostsPerDay,
        angles: campaignAngles,
        // targetAccounts stays empty for Blitz — publish targets are
        // derived from connectedAccounts − blitzDisabledAccountIds.
        startDate,
        totalPosts: initialPostsPerDay * DEFAULT_BLITZ.campaignLengthDays,
      })
      .returning();

    campaign = created;
  }

  if (!campaign) {
    return <p className="py-8 text-body text-muted-foreground">Could not initialize Blitz.</p>;
  }

  // ── Effective publish targets (derive-on-read) ────────────────────────
  // Compute what accounts Blitz will publish to for THIS render. If the
  // row still has the legacy `targetAccounts` snapshot and no
  // `blitzDisabledAccountIds` yet, resolveBlitzTargetAccounts migrates
  // the snapshot into an equivalent exclusion list once and returns
  // needsPersist=true. Any subsequent connect/disconnect happens
  // transparently because the effective list is re-derived every read.
  const accountResolve = resolveBlitzTargetAccounts({
    connectedAccounts: connectedAccounts as any,
    blitzDisabledAccountIds: (campaign.blitzDisabledAccountIds as string[] | null | undefined) ?? null,
    legacyTargetAccounts: (campaign.targetAccounts as any[]) || null,
  });
  if (accountResolve.needsPersist) {
    await db
      .update(campaignSchema)
      .set({ blitzDisabledAccountIds: accountResolve.disabledIds })
      .where(eq(campaignSchema.id, campaign.id));
    (campaign as any).blitzDisabledAccountIds = accountResolve.disabledIds;
  }

  // Ensure content mix includes ALL available content types, not just the
  // legacy 3-type default. This auto-expands existing campaigns created
  // before the fix so they also use talking_head templates from the library.
  const DEFAULT_MIX_KEYS = new Set(['slideshow', 'greenScreen', 'videoHook', 'talkingHead', 'videoHookDemo', 'ugc']);
  const existingMix = (campaign.contentMix || {}) as Record<string, number>;
  const missingTypes = [...DEFAULT_MIX_KEYS].filter((k) => {
    const v = existingMix[k];
    return v === undefined || v === null;
  });
  if (missingTypes.length > 0) {
    const base = 100 / (Object.keys(existingMix).length + missingTypes.length);
    for (const k of missingTypes) {
      existingMix[k] = Math.round(base);
    }
    // Normalize to 100
    const total = Object.values(existingMix).reduce((s, v) => s + v, 0);
    if (total !== 100 && Object.keys(existingMix).length > 0) {
      const first = Object.keys(existingMix)[0];
      if (first) {
        existingMix[first]! += 100 - total;
      }
    }
    await db.update(campaignSchema).set({ contentMix: existingMix }).where(eq(campaignSchema.id, campaign.id));
    campaign.contentMix = existingMix;
  }

  // Fetch content items for the campaign
  const rows = await db
    .select({
      cc: campaignContentSchema,
      ci: contentItemSchema,
      angle: contentAngleSchema,
    })
    .from(campaignContentSchema)
    .leftJoin(contentItemSchema, eq(campaignContentSchema.contentItemId, contentItemSchema.id))
    .leftJoin(contentAngleSchema, eq(contentItemSchema.angleId, contentAngleSchema.id))
    .where(eq(campaignContentSchema.campaignId, campaign.id))
    .orderBy(campaignContentSchema.sequenceIndex);

  const contentItems = rows.map((row: any) => ({
    ...(row.ci || {}),
    angleName: row.angle?.name || null,
    sequenceIndex: row.cc.sequenceIndex,
    scheduledDate: row.cc.scheduledDate ? new Date(row.cc.scheduledDate).toISOString().slice(0, 10) : undefined,
    scheduledTime: row.cc.scheduledTime,
    isRolled: row.cc.isRolled,
  }));

  // ── Server-side daily limit check ──
  // Count today's content items with statuses that consume the daily
  // allowance. Calculated here (not just client-side) so the limit
  // survives a full page refresh even if sessionStorage is cleared.
  // Must match the server-side filter in utils.ts — 'rejected' counts,
  // 'failed' does not (Bug 1: rejected cards should not trigger refill).
  const DAILY_LIMIT_STATUSES = new Set(['pending_review', 'approved', 'skipped', 'rejected']);
  const todayCount = contentItems.filter(
    (i: any) => i.status && DAILY_LIMIT_STATUSES.has(String(i.status)),
  ).length;
  const postsPerDay = campaign.postsPerDay || 10;
  const dailyLimitReached = todayCount >= postsPerDay;

  return (
    <BlitzDailyView
      campaign={campaign as any}
      initialContentItems={contentItems as any}
      dailyLimitReached={dailyLimitReached}
      dailyLimitCount={todayCount}
      dailyLimit={postsPerDay}
      effectiveTargetAccountIds={accountResolve.effectiveTargets.map(t => t.accountId)}
      disabledAccountIds={accountResolve.disabledIds}
    />
  );
}
