// Curated themes — each maps to an Unsplash search query
// The query is used server-side via /api/media-library/curated?theme=...
// Preview images are fetched live from Unsplash using the access key

export type CuratedTheme = {
  id: string;
  name: string;
  query: string; // Unsplash search term
  previewUrl?: string; // optional static fallback
};

export const CURATED_THEMES: CuratedTheme[] = [
  { id: 'artificial-intelligence', name: 'Artificial Intelligence', query: 'artificial intelligence technology' },
  { id: 'startup', name: 'Startup', query: 'startup office modern workspace' },
  { id: 'entrepreneurship', name: 'Entrepreneurship', query: 'entrepreneur hustle business growth' },
  { id: 'productivity', name: 'Productivity', query: 'productivity desk setup focus' },
  { id: 'marketing', name: 'Marketing', query: 'digital marketing strategy' },
  { id: 'social-media', name: 'Social Media', query: 'social media content creator' },
  { id: 'finance', name: 'Finance', query: 'finance money investment banking' },
  { id: 'investing', name: 'Investing', query: 'stock market investing wealth' },
  { id: 'business-growth', name: 'Business Growth', query: 'business growth success chart' },
  { id: 'leadership', name: 'Leadership', query: 'leadership team meeting conference' },
  { id: 'remote-work', name: 'Remote Work', query: 'remote work home office laptop' },
  { id: 'technology', name: 'Technology', query: 'technology innovation digital future' },
  { id: 'saas', name: 'SaaS', query: 'software dashboard app interface' },
  { id: 'ecommerce', name: 'E-Commerce', query: 'ecommerce shopping online retail' },
  { id: 'fitness', name: 'Fitness', query: 'fitness gym workout training' },
  { id: 'wellness', name: 'Wellness', query: 'wellness mindfulness meditation calm' },
  { id: 'health', name: 'Health', query: 'health nutrition healthy lifestyle' },
  { id: 'food', name: 'Food & Cooking', query: 'food cooking gourmet restaurant' },
  { id: 'travel', name: 'Travel', query: 'travel adventure explore world' },
  { id: 'nature', name: 'Nature', query: 'nature landscape mountains forest' },
  { id: 'luxury', name: 'Luxury', query: 'luxury lifestyle premium elegant' },
  { id: 'real-estate', name: 'Real Estate', query: 'real estate property architecture modern home' },
  { id: 'education', name: 'Education', query: 'education learning books university' },
  { id: 'creativity', name: 'Creativity', query: 'creativity art design studio' },
  { id: 'design', name: 'Design', query: 'graphic design typography branding' },
  { id: 'photography', name: 'Photography', query: 'photography camera portrait studio' },
  { id: 'fashion', name: 'Fashion', query: 'fashion style clothing modern' },
  { id: 'beauty', name: 'Beauty', query: 'beauty skincare makeup cosmetics' },
  { id: 'motivation', name: 'Motivation', query: 'motivation inspiration success mindset' },
  { id: 'minimalism', name: 'Minimalism', query: 'minimalism minimal clean simple aesthetic' },
  { id: 'innovation', name: 'Innovation', query: 'innovation future technology breakthrough' },
  { id: 'future-tech', name: 'Future Tech', query: 'futuristic technology cyberpunk neon' },
  { id: 'web-development', name: 'Web Development', query: 'web development coding programming' },
  { id: 'mobile-apps', name: 'Mobile Apps', query: 'mobile app smartphone interface ux' },
  { id: 'personal-branding', name: 'Personal Branding', query: 'personal branding professional headshot' },
  // { id: 'content-creation', name: 'Content Creation', query: 'content creator studio filming' },
  { id: 'content-creation', name: 'Content Creation', query: 'camera filming creator' },
  { id: 'creator-economy', name: 'Creator Economy', query: 'influencer creator digital media' },
  { id: 'small-business', name: 'Small Business', query: 'small business local shop owner' },
  { id: 'customer-success', name: 'Customer Success', query: 'customer service team support' },
  { id: 'teamwork', name: 'Teamwork', query: 'teamwork collaboration office diverse' },
  { id: 'community', name: 'Community', query: 'community people gathering social' },
  { id: 'desk-setup', name: 'Desk Setup', query: 'desk setup workspace productivity aesthetic' },
  // { id: 'digital-nomad', name: 'Digital Nomad', query: 'digital nomad travel laptop cafe beach' },
  { id: 'digital-nomad', name: 'Digital Nomad', query: 'remote work laptop travel' },
  { id: 'cryptocurrency', name: 'Cryptocurrency', query: 'cryptocurrency bitcoin blockchain digital currency' },
  { id: 'blockchain', name: 'Blockchain', query: 'blockchain decentralized network technology' },
  { id: 'cybersecurity', name: 'Cybersecurity', query: 'cybersecurity hacker privacy data protection' },
  { id: 'data-analytics', name: 'Data Analytics', query: 'data analytics charts dashboard visualization' },
  { id: 'sustainability', name: 'Sustainability', query: 'sustainability green energy environment eco' },
  { id: 'mental-health', name: 'Mental Health', query: 'mental health therapy self care calm' },
  { id: 'career-growth', name: 'Career Growth', query: 'career growth professional development promotion' },
  { id: 'networking', name: 'Networking', query: 'networking business event conference handshake' },
  // { id: 'airport-aesthetic', name: 'Airport Aesthetic', query: 'airport travel terminal flight aesthetic' },
  { id: 'airport-aesthetic', name: 'Airport Aesthetic', query: 'airport travel' },
  { id: 'animals', name: 'Animals', query: 'animals wildlife pets cute' },
  { id: 'art', name: 'Art', query: 'art gallery painting contemporary museum' },
  { id: 'gaming', name: 'Gaming', query: 'gaming esports video games setup neon' },
  { id: 'gym', name: 'Gym', query: 'gym weights exercise training bodybuilding' },
  { id: 'female-aesthetics', name: 'Female Aesthetics', query: 'female aesthetic lifestyle elegant woman' },
  { id: 'female-selfies', name: 'Female Selfies', query: 'woman portrait selfie lifestyle fashion' },
  { id: 'friendship', name: 'Friendship & Community', query: 'friends community group people laughing' },
  { id: 'generic-lifestyle', name: 'Generic Lifestyle', query: 'lifestyle everyday moments authentic living' },
  // { id: 'golf', name: 'Golf', query: 'golf course sport luxury green' },
  { id: 'golf', name: 'Golf', query: 'golf course' },
  { id: 'cars', name: 'Cars & Automotive', query: 'luxury car sports automotive road drive' },
  { id: 'coffee', name: 'Coffee Culture', query: 'coffee cafe barista latte aesthetic' },
  { id: 'books', name: 'Books & Knowledge', query: 'books reading library knowledge study' },
];