/**
 * Text-length limits for editor-overlay text.
 *
 * Blitz hook/body/cta can arrive as multi-line paragraphs generated by the
 * LLM, which overflow the Remotion canvas and clip awkwardly at the bottom
 * edge. These are the caps the compiled MP4 enforces.
 *
 * Character limits are conservative for portrait (9:16) at fontSize 48;
 * the compositions honor whatever fontSize the user picks in the editor
 * so these numbers are calibrated for the default.
 *
 * ── KEEP IN SYNC ──────────────────────────────────────────────────────────
 * `hook` is mirrored by DEFAULT_CAPTION_BUDGET in lib/blitz/apply-brand-voice.
 * That budget is what generation is TOLD to write within; this is what the
 * renderer will actually fit. If generation is allowed more than the renderer
 * enforces, copy clears the preview and then gets cut when the video bakes —
 * which is exactly how a trailing ellipsis reached published captions. Change
 * the two together, always.
 */

export const TEXT_LIMITS = {
  hook: 120,
  body: 160,
  cta: 40,
} as const;

/**
 * Fit a string to `limit` characters WITHOUT appending an ellipsis.
 *
 * This used to end with "…", which is how a trailing ellipsis reached baked
 * video captions. A caption that visibly trails off reads as broken software.
 * The real guarantee is upstream — generation is given this same budget (see
 * DEFAULT_CAPTION_BUDGET in lib/blitz/apply-brand-voice.ts) so copy arrives
 * short enough to render whole, and this is only the last-resort net for
 * legacy rows and hand-edited text.
 *
 * When it must cut, it prefers ending on a complete sentence, so the result
 * reads as a deliberately short line.
 *
 * Name kept for its callers; the ellipsis behaviour is deliberately gone.
 */
export function truncateWithEllipsis(input: string | undefined | null, limit: number): string {
  if (!input) {
    return '';
  }
  const trimmed = String(input).trim();
  if (trimmed.length <= limit) {
    return trimmed;
  }

  const slice = trimmed.slice(0, limit);

  // A whole sentence inside the budget beats a severed clause.
  const lastSentenceEnd = Math.max(
    slice.lastIndexOf('. '),
    slice.lastIndexOf('! '),
    slice.lastIndexOf('? '),
  );
  if (lastSentenceEnd > limit * 0.3) {
    return slice.slice(0, lastSentenceEnd + 1).trimEnd();
  }
  if (/[.!?]$/.test(slice.trimEnd())) {
    return slice.trimEnd();
  }

  // Otherwise cut on a word boundary and drop dangling punctuation so the
  // line ends cleanly. Only respect the boundary if it's reasonably far in —
  // avoids a single stub when the first word exceeds the limit.
  const lastSpace = slice.lastIndexOf(' ');
  const cut = lastSpace > limit * 0.5 ? slice.slice(0, lastSpace) : slice;
  return cut.trimEnd().replace(/[\s,;:—–-]+$/, '');
}

export function limitHook(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.hook);
}

export function limitBody(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.body);
}

export function limitCta(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.cta);
}

/**
 * `previewMode`-aware variants — return the raw string when
 * `previewMode === true` (the live browser preview uses CSS `line-clamp`
 * / overflow to handle long text, so it doesn't need the ellipsis chop).
 * Compile-to-MP4 mounts never set `previewMode`, so baked Remotion
 * output still gets truncated.
 */
export function limitHookMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitHook(input);
}

export function limitBodyMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitBody(input);
}

export function limitCtaMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitCta(input);
}
