/**
 * Text-length limits for editor-overlay text.
 *
 * Bug 2 fix — Blitz hook/body/cta can arrive as multi-line paragraphs
 * generated by the LLM, which overflow the Remotion canvas and clip
 * awkwardly at the bottom edge. Truncate at render-time with an
 * ellipsis so overlays always fit their frame.
 *
 * Character limits are conservative for portrait (9:16) at fontSize 48;
 * the compositions honor whatever fontSize the user picks in the editor
 * so these numbers are calibrated for the default.
 */

export const TEXT_LIMITS = {
  hook: 80,
  body: 160,
  cta: 40,
} as const;

/**
 * Truncate a string to `limit` characters, appending "…" when the
 * source is longer. Trims trailing whitespace and cuts on the last
 * word boundary within the limit so we don't split a word.
 */
export function truncateWithEllipsis(input: string | undefined | null, limit: number): string {
  if (!input) return '';
  const trimmed = String(input).trim();
  if (trimmed.length <= limit) return trimmed;

  const slice = trimmed.slice(0, limit);
  const lastSpace = slice.lastIndexOf(' ');
  // Only respect a word boundary if it's reasonably far into the slice —
  // avoids "F…" when the first word is longer than the limit.
  const cut = lastSpace > limit * 0.6 ? slice.slice(0, lastSpace) : slice;
  return `${cut.trimEnd()}…`;
}

export function limitHook(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.hook);
}

export function limitBody(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.body);
}

export function limitCta(input: string | undefined | null): string {
  return truncateWithEllipsis(input, TEXT_LIMITS.cta);
}

/**
 * `previewMode`-aware variants — return the raw string when
 * `previewMode === true` (the live browser preview uses CSS `line-clamp`
 * / overflow to handle long text, so it doesn't need the ellipsis chop).
 * Compile-to-MP4 mounts never set `previewMode`, so baked Remotion
 * output still gets truncated.
 */
export function limitHookMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitHook(input);
}

export function limitBodyMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitBody(input);
}

export function limitCtaMaybe(input: string | undefined | null, previewMode?: boolean): string {
  return previewMode ? (input ? String(input) : '') : limitCta(input);
}
